export { Navigation } from "./Navigation/Navigation";
export { Slider } from "./Slider/Slider";
export { Plans } from "./Plans/Plans";
export { AboutUs } from "./AboutUs/AboutUs";
export { Location } from "./Location/Location";
export { Specifications } from "./Specifications/Specifications";
export { Contact } from "./Contact/Contact";
export { Partners } from "./Partners/Partners";
export { Footer } from "./Footer/Footer";
